basic.forever(function () {
    if (tinkercademy.PIR(DigitalPin.P15)) {
        basic.showIcon(IconNames.Heart)
        music.playMelody("C5 B A G F E D C ", 120)
        wuKong.setAllMotor(-24, 81)
        basic.pause(1000)
        wuKong.setAllMotor(24, -81)
        basic.pause(1000)
        wuKong.setServoAngle(wuKong.ServoTypeList._360, wuKong.ServoList.S0, 270)
        basic.pause(1000)
        wuKong.setServoAngle(wuKong.ServoTypeList._360, wuKong.ServoList.S0, 90)
        basic.pause(1000)
        wuKong.setServoSpeed(wuKong.ServoList.S2, 80)
        basic.pause(1000)
        wuKong.setServoSpeed(wuKong.ServoList.S2, -80)
        basic.pause(1000)
        music.playMelody("C D E F G A B C5 ", 120)
        wuKong.stopAllMotor()
    } else {
        basic.showIcon(IconNames.Sad)
    }
    OLED.init(128, 64)
    OLED.writeStringNewLine("00                 00")
    OLED.writeStringNewLine("  00             00")
    OLED.writeStringNewLine("    00         00")
    OLED.writeStringNewLine("      00    000")
    OLED.writeStringNewLine("        0000 ")
    basic.pause(2000)
})
